### ISSUE TITLE
tracking issue:overriding ins tag of one user with another user is not working.it works on http://nytimes.github.io/ice/demo/

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [loopindex/ckeditor-track-changes#84]
text1 inserted by user1 and user2 wants to override the text1 with text2 text1 is rejected but i unable to write further.

**Comment by imdfl** [comment]
Hello Amara,

It would help if you'd provide a step by step description - what user 1 types, how the current user is switched to user2, where the text caret is, what is erased, what is typed etc. Thanks

**Comment by Amara-Balakrishna1** [comment]
step1:- user1 roger wrote text "editor" .
step2:- he changed the user to david.
step3: selected text "editor" which is inserted by roger shift+left arrow.
step4:- started writing editor not allows it.

**Comment by imdfl** [comment]
Thanks for the detailed description.
A fix has been committed to the dev branch. Would you be so kind as to verify that it works for you?

**Comment by Amara-Balakrishna1** [comment]
not fixed getting the same issue.if fixed please give the link.

**Comment by imdfl** [comment]
Just to be clear - did you test using the code in the dev branch, or did you try one of our demo pages?

**Comment by Amara-Balakrishna1** [comment]
demo page.

**Comment by imdfl** [comment]
OK, I'm sorry for not being clear before.
When I wrote "A fix has been committed to the dev branch" I meant that it was currently in the dev branch and not deployed anywhere. If you can't use the code from the dev branch, just follow this issue and I'll post an update when the fix is committed to master and available in the demo page.

**Comment by imdfl** [comment]
Please check the loopindex demo page, should be fixed there.

**Comment by Amara-Balakrishna1** [comment]
done...
